version: "3.2"

services:
  database:
    restart: always
    image: mysql:latest
    ports:
      - 33061:33061
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql-datavolume:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root

volumes:
  mysql-datavolume:
    driver: local
